### ISSUE TITLE
Planungsbesprechung terminieren

### ISSUE THREAD

**Issue by escapedraccoon** [escapedraccoon/haw-hof-vinf4-webdev1-testat2#1]
### Planungsbesprechung

- Termin: tbd
- Uhrzeit: tbd

- Ort: Discord

@noethbne

**Comment by voidravens** [comment]
Wie wäre es mit Samstag? Wann genau wär mir Wurst

**Comment by escapedraccoon** [comment]
Ich würde auch für **im Laufe des Samstags** votieren. Aber nicht nach 18 Uhr, da hab ich ggf. Termine.

**Comment by escapedraccoon** [comment]
- [X] Accepted

Wegen mir jedenfalls. @noethbne ?

**Comment by noethbne** [comment]
Puh 16 Uhr bin ich Samstag normal noch unterwegs... Aber bin normal ab halb 5 oder so Zuhause

**Comment by escapedraccoon** [comment]
- [X] Termin: Samstag, 30.04.2022
- [X] Uhrzeit: 17:00
- [X] Ort: Discord
