### ISSUE TITLE
HTML Gerüst für Scoreboard-Anzeige

### ISSUE THREAD

**Issue by escapedraccoon** [escapedraccoon/haw-hof-vinf4-webdev1-testat2#10]

**Comment by voidravens** [comment]
Habe mal ein erstes Gerüst gebaut. Feedback willkommen. 

Bin mit dem Hintergrundbild und wie es sich verhält nicht glücklich aber das Design kann man später noch machen.

Hauptsache man hat erst mal was womit man arbeiten kann
