### ISSUE TITLE
[Scoreboard] Eingabedaten prüfen

### ISSUE THREAD

**Issue by escapedraccoon** [escapedraccoon/haw-hof-vinf4-webdev1-testat2#17]
Sollen Eingabe-Daten für `$_GET` für das Scoreboard noch "irgendwie" überprüft werden? Oder verlassen wir uns drauf, dass niemand PHP/SQL Befehle in das Namens-Feld tippt?

**Comment by voidravens** [comment]
Wenn wir Zeit haben hätte ich ne überprüfung eingebaut, aber an sich hätte ich es erstmal "aufgehübscht" und Intuitiver gestaltet

**Comment by escapedraccoon** [comment]
Auf was genau hättest du denn geprüft bzw. wo und an welcher Stelle?

**Comment by voidravens** [comment]
Ich hätte gesagt prüfen sobald es weggeschickt wird. Generell auf alles was SQL als Befehl interpretieren könnte. Wenn man es wirklich sicher machen will müsste man das prüfen serverseitig machen.... Ich fürchte das wird ein Fass ohne Boden. Ich hätte gesagt wir gehen mal davon aus, dass der Prof nicht so was erwartet. Und wenn doch haben wir halt ein, zwei Pünktchen weniger.
