### ISSUE TITLE
[Game Engine] Wann soll Eintrag im Scoreboard erfolgen.

### ISSUE THREAD

**Issue by escapedraccoon** [escapedraccoon/haw-hof-vinf4-webdev1-testat2#19]
Game Mechanics einer Prüfung unterziehen.
Soll ein Eintrag im Scoreboard immer möglich sein - oder nur wenn man gegen den (schweren!) Bot gewonnen hat? 
Ich bin für immer. Man ist durch wenig Punkte eh gestraft.

**Comment by voidravens** [comment]
Ruhig immer.

An sich wäre es ganz nett wenn man statt einen Score zu submitten, auch zurück ins Hauptmenü oder gleich ein neues Spiel starten könnte

**Comment by escapedraccoon** [comment]
Ja - wir haben uns jetzt, weil eh schon nicht viel Platz ist, für die 1-Button Lösung entschieden. Theoretisch kann man aber auch neben dem Submit Button noch schnell ein paar weitere Buttons spawnen.
Den Hauptmenü Button könnten wir auch gleich lassen und nicht zum Scoreboard wechseln. Aber ich find diesen "Umweg" über das Hauptmenü jetzt nicht untypisch. Ist ja eigentlich bei vielen Spielen normal so, dass man erstmal zum Scoreboard gelangt und dann Hauptmenü und weiter. 
Egal ob Age Of Empires oder Valorant, wird eig. oft so gelöst.

**Comment by voidravens** [comment]
Dann lassen wir das jetzt einfach so wie es schon ist. Funktioniert ja schließlich stört nicht und bedeutet wenn nur mehraufwand mit wenig Gewinn.
