### ISSUE TITLE
Front-End-Design Entwurf erstellen

### ISSUE THREAD

**Issue by escapedraccoon** [escapedraccoon/haw-hof-vinf4-webdev1-testat2#2]

**Comment by escapedraccoon** [comment]
This issue has to wait 'til #6 is finished.

**Comment by escapedraccoon** [comment]
#6 ist nun abgeschlossen, weiter hier.

**Comment by voidravens** [comment]
Designentwurf für Spielfeld (mit Papier und Bleistift) erstellt. Wiki dementsprechend erweitert
