### ISSUE TITLE
[Language] Mix aus DE und EN Text

### ISSUE THREAD

**Issue by escapedraccoon** [escapedraccoon/haw-hof-vinf4-webdev1-testat2#22]
Irgendwie ist in unser Spiel, je nachdem wer entwickelt hat, ein lustiger Mix aus DE/EN locales gekommen. Vielleicht sollte man das noch anpassen.

**Comment by noethbne** [comment]
Ah wir behaupten einfach das ist  neudeutsch und fertig.

**Comment by escapedraccoon** [comment]
Behoben!
