### ISSUE TITLE
Test-Daten als SQL Export bereitstellen

### ISSUE THREAD

**Issue by escapedraccoon** [escapedraccoon/haw-hof-vinf4-webdev1-testat2#3]

**Comment by escapedraccoon** [comment]
Testdaten werden von @voidravens in phpMyAdmin erstellt und im Ordner `db/` als .sql-Dump bereitgestellt.

**Comment by voidravens** [comment]
Datenbank mit Tabelle mit 25 (Test)-Monstern ist angelegt. Andere Tabelle enthält Struktur für Scoreboard (Name und Rundenzahl) damit sie später befüllt werden kann.
