### ISSUE TITLE
Kaffee kochen

### ISSUE THREAD

**Issue by escapedraccoon** [escapedraccoon/haw-hof-vinf4-webdev1-testat2#4]

**Comment by noethbne** [comment]
Pls buy zis 
https://www.amazon.de/Aladdin-Vakuumisoliert-Auslaufsicher-Spülmaschinenfest-Isolierbecher/dp/B07PJXXSL4/ref=sr_1_7?keywords=aladdin+thermobecher+0%2C35&qid=1651559357&sprefix=aladdin+ther%2Caps%2C113&sr=8-7

**Comment by escapedraccoon** [comment]
no

**Comment by noethbne** [comment]
Fuck you du Hund
