### ISSUE TITLE
Design-Entwurf überarbeiten

### ISSUE THREAD

**Issue by escapedraccoon** [escapedraccoon/haw-hof-vinf4-webdev1-testat2#6]

**Comment by escapedraccoon** [comment]
Design-Entwurf muss an die Vorgaben von C.Schaller angepasst werden um das Kartenspiel abzubilden.

**Comment by voidravens** [comment]
Ich kümmer mich heute drum, hatte bisher nicht genug Zeit :/

**Comment by escapedraccoon** [comment]
Dokumentation erweitert, befindet sich in `/docs/`.
